# permissions for end users to view horus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horus-viewer-role
rules:
- apiGroups:
  - horus.io
  resources:
  - horus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - horus.io
  resources:
  - horus/status
  verbs:
  - get
